name: msnn-env
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.5
  - matplotlib
  - scipy
  - pip
  - tqdm
  - libprotobuf=3.20.3
  - cudatoolkit=11.2.2
  - cudnn=8.1
  - pip:
      - tensorflow==2.10
      - pillow==9.0.0
