name: msnn-env
channels:
    - defaults
    - conda-forge
    - pip
dependencies:
    - python=3.9
    - numpy
    - matplotlib
    - scipy
    - pip
    - tqdm
    - ipykernel
    - pip:
          - tensorflow==2.16.1
          - tensorflow-probability==0.24.0
          - tf-keras
          - argparse
