name: msnn-env
channels:
    - defaults
    - conda-forge
    - pip
dependencies:
    - python=3.9
    - numpy
    - matplotlib
    - scipy
    - pip
    - tqdm
    - ipykernel
    - tensorflow>=2.18
    - pip:
          - tensorflow-probability
          - tf-keras
          - argparse
